# Generated by Django 6.0.4 on 2026-05-03 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharModeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_name', models.CharField(max_length=10, verbose_name='왕 이름')),
                ('hanja_name', models.CharField(max_length=10, verbose_name='왕 한자 이름')),
                ('birth_to_death', models.CharField(max_length=10, verbose_name='생애')),
                ('keyword1', models.CharField(blank=True, max_length=50, null=True, verbose_name='키워드1')),
                ('keyword2', models.CharField(blank=True, max_length=50, null=True, verbose_name='키워드2')),
                ('keyword3', models.CharField(blank=True, max_length=50, null=True, verbose_name='키워드3')),
                ('summary', models.TextField(max_length=200, verbose_name='왕 정보 요약')),
                ('img_url', models.ImageField(upload_to='characters/')),
            ],
            options={
                'db_table': 'char_mode_info',
                'ordering': ['kor_name'],
            },
        ),
        migrations.CreateModel(
            name='CharRoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('king_state', models.CharField(default='평온함', max_length=20, verbose_name='왕의 기분을 표시')),
                ('message_length', models.CharField(choices=[('short', '짧게'), ('normal', '보통'), ('long', '길게'), ('very_long', '매우 길게')], default='normal', max_length=20, verbose_name='응답 길이')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.charmodeinfo', verbose_name='캐릭터 ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저 ID')),
            ],
            options={
                'db_table': 'char_room_settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('situation', '상황'), ('user', '사용자'), ('character', '캐릭터')], max_length=20, verbose_name='메시지 타입')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='characters.charroomsettings')),
            ],
            options={
                'db_table': 'char_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personality', models.CharField(default='모든 행동에 민감하게 반응하는 성격', max_length=20, verbose_name='성격')),
                ('identity', models.CharField(choices=[('farmer', '농부'), ('scholar', '유생'), ('official', '관료'), ('general', '장수'), ('merchant', '상인'), ('physician', '의원'), ('eunuch', '내관')], default='farmer', max_length=20, verbose_name='신분')),
                ('values', models.CharField(default='밥 먹는 것이 최고고 모든 문제는 밥으로 해결 가능하다.', max_length=500, verbose_name='가치관')),
                ('first_scene', models.TextField(default='밥 먹다가 왕에게 갑자기 호출됐다.', max_length=1000, verbose_name='최초 상황')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'char_persona',
            },
        ),
        migrations.AddField(
            model_name='charroomsettings',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.persona', verbose_name='적용된 페르소나 ID'),
        ),
    ]
